title: Valinor Earth Blog
logo: '/assets/valinor-earth-logo-text.png'
description: 'Information and Readings helping Curb Climate Change.'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Jekyll settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

sass:
  sass_dir: _sass
  style: compressed